/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.Console;
import java.util.List;
import java.util.ArrayList;
import java.util.Random;
public class App {


public static void main(String[] args) {
        Console myConsole=System.console();
        Random myRandomGenerator = new Random();
        List<String> myWords=new ArrayList<String>();
        
        myWords.add("snake");
        myWords.add("tiger");
        myWords.add("shark");
        myWords.add("whale");
        myWords.add("viper");
        String myWord=myWords.get(myRandomGenerator.nextInt(5));
        System.out.println("I am a 5 letter word and I am also an animal.Can you guess who I am:");
        String userWord=myConsole.readLine();
        HangMan newGame=new HangMan(userWord);

        String[] userLetters=newGame.getUser().split("");
        System.out.println(userLetters[1]);
        System.out.println(myWord);


}
}
